enum {
    COUNTER_BOOTP,
    COUNTER_PXE,
    COUNTER_DHCPACK,
    COUNTER_DHCPDECLINE,
    COUNTER_DHCPDISCOVER,
    COUNTER_DHCPINFORM,
    COUNTER_DHCPNAK,
    COUNTER_DHCPOFFER,
    COUNTER_DHCPRELEASE,
    COUNTER_DHCPREQUEST,
    COUNTER_NOANSWER,
    COUNTER_MAX,
};

#ifdef HAVE_METRICS

volatile u32 metrics[COUNTERS];

#define METRICS_INCREMENT(field) metrics[field]++;

#else

#define METRICS_INCREMENT(field) (void)0

#endif /* HAVE_METRICS */
